excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: https://boi.yahyabd.xyz
title: ইপাব সমগ্র
tagline: "বাঙলা ইপাব লাইব্রেরি"
description: "বাঙলা ইপাব লাইব্রেরি"
paginate: 48
include: ['_authors']
permalink: /library/:title/
relative_permalinks: false

gems: [jekyll-paginate]
